name: Build CardAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        config: [release]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Build CardAction
      run: |
        .\build.bat ${{ matrix.arch }} ${{ matrix.config }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CardAction-${{ matrix.arch }}-${{ matrix.config }}
        path: build/${{ matrix.arch }}/${{ matrix.config }}/CardAction.exe